language: node_js
node_js:
  - "12.21.0"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: main
  target-branch: gh-pages
  local_dir: dist